modLoader = "kotlinforforge"
loaderVersion = "[6.2,)"
license = "Insert License Here"
authors = "Unitei"

[[mods]]
modId = "effective"
version = "${version}"
displayName = "${name}"
description = '''
${description}
'''

[[mixins]]
config = "effective-common.mixins.json"

[[mixins]]
config = "effective.mixins.json"

[[dependencies.effective]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.effective]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.effective]]
modId = "velvet"
type = "optional"
versionRange = "[0.4,)"
ordering = "NONE"
side = "CLIENT"