# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
effectiveModId = effective
effectiveModName = Effective
effectiveModDescription = Client-side mod designed to improve Minecraft's ambience through particles, visual effects and sounds.
effectiveModVersion = 1.0.8+26.1.2
effectiveMavenGroup = com.oneworldstuddo.effective

modId = emixx
modVersion = 1.0.0
mavenGroup = com.oneworldstuddo.emixx

enabledPlatforms = fabric,neoforge

# Minecraft properties
minecraftVersion = 26.1.2

# Dependencies
fabricLoaderVersion = 0.18.5
neoForgeVersion = 26.1.2.36-beta

kotlinForNeoForgeVersion = 6.2.0
fabricLanguageKotlinVersion = 1.15.0+kotlin.2.2.21
mixinExtrasVersion = 0.4.1
forgeConfigApiPortVersion = 26.1.3
configuredForgeVersion = 5873783
velvetVersion = 0.4.1
sparkweaveVersion = 0.508.1
